### ISSUE TITLE
The timer is displayed on top of the clock module

### ISSUE THREAD

**Issue by Dimasua** [Klettner/MMM-StopwatchTimer#2]
Hi, thank you for this module! There is one issue, the module once activated from MM-Remote, is not shown on the black screen, but on top of the clock module. Is that expected behavior? I guess that the MM should hide all the modules and display the timer/stopwatch.

**Comment by Klettner** [comment]
Hi, the expected behaviour is that once activated, the background is completely black and you can only see the timer/stopwatch. I just checked and it works as expected with my set up. 
Could you please try if sending an alert works as expected? This is important to know, as MMM-StopwatchTimer is based on the code of that module. 
Please also try to place it as the first module in your MagicMirror/config/config.js file and let me know if that makes a difference.
